apiVersion: v2
appVersion: 2.1.0
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 10.2.0
- condition: rabbitmq.enabled
  name: rabbitmq
  repository: https://charts.bitnami.com/bitnami
  version: 8.5.4
description: A Helm Chart for deploying the polylogyx endpoint security platform
home: https://github.com/Rohini9596/eiq-er-ce/tree/helm-chart/charts
keywords:
- polylogyx
- osquery
- esp
- edr
- endpoint security platform
- osquery fleet manager
- eclecticiq
name: polylogyx-esp
version: 0.0.11
